package: rexfactor
version: '0.1.26'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/rexfactor

page:
    title: rexfactor
    icon: rex-icon fa-fast-forward
    perm: admin

    subpages:
        target-chooser:
            title: 'AddOn'
            hidden: true
        use-case:
            title: 'Use case'
            hidden: true
        preview:
            title: 'Preview'
            hidden: true
        apply:
            title: 'Summary'
            hidden: true
        intro:
            title: 'Intro'
            href: https://staabm.github.io/2023/04/09/rexfactor-introduction.html
            itemClass: pull-right
            icon: rex-icon fa-book

requires:
    php:
        version: '>=7.4, <8.3'
    redaxo: '^5.14'

installer_ignore:
    - rector.pnp
